-- Phase 5: starter topic seeds so pick_secret returns real words.
-- The full content database (hundreds of topics) lands in Phase 12.

INSERT INTO topics (word, category, difficulty, mode) VALUES
-- Classic / easy (20) -------------------------------------------------------
('Pizza', 'food', 'easy', 'classic'),
('Burger', 'food', 'easy', 'classic'),
('Cricket', 'sports', 'easy', 'classic'),
('Football', 'sports', 'easy', 'classic'),
('Tea', 'food', 'easy', 'classic'),
('Coffee', 'food', 'easy', 'classic'),
('Dog', 'animals', 'easy', 'classic'),
('Cat', 'animals', 'easy', 'classic'),
('Car', 'travel', 'easy', 'classic'),
('Phone', 'technology', 'easy', 'classic'),
('Movie', 'entertainment', 'easy', 'classic'),
('Song', 'entertainment', 'easy', 'classic'),
('Birthday', 'daily-life', 'easy', 'classic'),
('Rain', 'nature', 'easy', 'classic'),
('Beach', 'travel', 'easy', 'classic'),
('Mountain', 'nature', 'easy', 'classic'),
('Train', 'travel', 'easy', 'classic'),
('Aeroplane', 'travel', 'easy', 'classic'),
('Doctor', 'work', 'easy', 'classic'),
('School', 'school', 'easy', 'classic'),
-- Classic / medium (10) ------------------------------------------------------
('Cappuccino', 'food', 'medium', 'classic'),
('Smartphone', 'technology', 'medium', 'classic'),
('Headphones', 'technology', 'medium', 'classic'),
('Backpack', 'travel', 'medium', 'classic'),
('Guitar', 'entertainment', 'medium', 'classic'),
('Library', 'school', 'medium', 'classic'),
('Museum', 'travel', 'medium', 'classic'),
('Picnic', 'daily-life', 'medium', 'classic'),
('Wedding', 'relationships', 'medium', 'classic'),
('Office', 'work', 'medium', 'classic'),
-- Classic / hard (10) ---------------------------------------------------------
('Barista', 'food', 'hard', 'classic'),
('Origami', 'entertainment', 'hard', 'classic'),
('Parachute', 'travel', 'hard', 'classic'),
('Thermometer', 'technology', 'hard', 'classic'),
('Telescope', 'technology', 'hard', 'classic'),
('Waterfall', 'nature', 'hard', 'classic'),
('Lighthouse', 'travel', 'hard', 'classic'),
('Igloo', 'nature', 'hard', 'classic'),
('Encore', 'entertainment', 'hard', 'classic'),
('Espresso', 'food', 'hard', 'classic'),
-- Desi Life / easy (12) ---------------------------------------------------------
('Chai', 'food', 'easy', 'desi-life'),
('Cricket', 'cricket', 'easy', 'desi-life'),
('Bollywood', 'bollywood', 'easy', 'desi-life'),
('Auto-rickshaw', 'travel', 'easy', 'desi-life'),
('Monsoon', 'festivals', 'easy', 'desi-life'),
('Diwali', 'festivals', 'easy', 'desi-life'),
('Holi', 'festivals', 'easy', 'desi-life'),
('Samosa', 'food', 'easy', 'desi-life'),
('Railway Station', 'travel', 'easy', 'desi-life'),
('Wedding', 'relationships', 'easy', 'desi-life'),
('Maggi', 'food', 'easy', 'desi-life'),
('College', 'college', 'easy', 'desi-life'),
-- Desi Life / medium (12) --------------------------------------------------------
('Cutting Chai', 'food', 'medium', 'desi-life'),
('Local Train', 'travel', 'medium', 'desi-life'),
('Street Food', 'food', 'medium', 'desi-life'),
('Hostel', 'college', 'medium', 'desi-life'),
('Coaching Classes', 'college', 'medium', 'desi-life'),
('Traffic Jam', 'daily-life', 'medium', 'desi-life'),
('Family Function', 'relationships', 'medium', 'desi-life'),
('Metro', 'travel', 'medium', 'desi-life'),
('Board Exams', 'school', 'medium', 'desi-life'),
('Cricket World Cup', 'cricket', 'medium', 'desi-life'),
('Goa Trip', 'travel', 'medium', 'desi-life'),
('Office Politics', 'work', 'medium', 'desi-life'),
-- Desi Life / hard (10) ------------------------------------------------------------
('IRCTC', 'travel', 'hard', 'desi-life'),
('UPI', 'technology', 'hard', 'desi-life'),
('Baraat', 'relationships', 'hard', 'desi-life'),
('Jugaad', 'daily-life', 'hard', 'desi-life'),
('Shaadi DJ', 'relationships', 'hard', 'desi-life'),
('PG Life', 'college', 'hard', 'desi-life'),
('CAT Exam', 'college', 'hard', 'desi-life'),
('Tiffin Dabba', 'food', 'hard', 'desi-life'),
('Rickshaw Meter', 'travel', 'hard', 'desi-life'),
('Gully Cricket', 'cricket', 'hard', 'desi-life'),
-- Desi Expert (10) --------------------------------------------------------------------
('Tatkal Booking', 'travel', 'expert', 'desi-expert'),
('Sleeper Class', 'travel', 'expert', 'desi-expert'),
('Platform Ticket', 'travel', 'expert', 'desi-expert'),
('Share Auto', 'travel', 'expert', 'desi-expert'),
('Vada Pav', 'food', 'expert', 'desi-expert'),
('Jalebi Fafda', 'food', 'expert', 'desi-expert'),
('Mohalla', 'daily-life', 'expert', 'desi-expert'),
('Load Shedding', 'daily-life', 'expert', 'desi-expert'),
('Doosra', 'cricket', 'expert', 'desi-expert'),
('Sangeet Night', 'relationships', 'expert', 'desi-expert'),
-- Hardcore (10) --------------------------------------------------------------------------
('LBW', 'cricket', 'hard', 'hardcore'),
('Googly', 'cricket', 'hard', 'hardcore'),
('Yorker', 'cricket', 'hard', 'hardcore'),
('Offside', 'sports', 'hard', 'hardcore'),
('Hat-trick', 'sports', 'hard', 'hardcore'),
('Penalty Shootout', 'sports', 'expert', 'hardcore'),
('Engagement Ceremony', 'relationships', 'expert', 'hardcore'),
('Pre-wedding Shoot', 'relationships', 'hard', 'hardcore'),
('Night Watchman', 'cricket', 'expert', 'hardcore'),
('Third Umpire', 'cricket', 'hard', 'hardcore');
